name: C lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  c-lint:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v7

    - name: Install NVML headers
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libnvidia-ml-dev

    - name: Compiler warnings
      run: find crates -type f -name '*.c' -exec clang-21 -std=c17 -Wall -Wextra -Wpedantic -Werror -fsyntax-only {} +

    - name: Clang-Tidy
      run: find crates -type f -name '*.c' -exec sh -c 'clang-tidy-21 --warnings-as-errors="*" "$@" -- -std=c17' _ {} +
